# Statically link the CRT so the shipped executable has no dependency on the Visual C++
# redistributable, which cannot be installed without Administrator privileges.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
